{{- if .Values.cloud.azure.isProvider -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: profisee-purview
data:
  ProfiseePurviewUrl: "https://systech-purview-lab.purview.azure.com"
  ProfiseePurviewTenantId: "17dcec91-66ec-4c4b-a988-473694df546c"
  ProfiseePurviewClientId: "systech_purview_admin"
  ProfiseePurviewClientSecret: "purviewkey"
{{- end }}
